version: 2.1

orbs:
  node: circleci/node@3.0.0
  # go: circleci/go@1.5.0

jobs:
  "node-run":
    working_directory: ~/oeis
    # Reuse Docker container specification
    executor: node/default
    steps:
      - checkout
      # Install the latest npm
      - node/install-npm
      # Install dependencies
      - node/install-packages:
          app-dir: ~/oeis/JavaScript
          cache-path: node_modules
          override-ci-command: npm i
      # No application is added on testing, so
      # I make tests run in a build process, not in a different process.
      - run:
          name: Test
          command: cd JavaScript && npm run test
  "go-run":
    working_directory: ~/oeis
    docker:
      - image: circleci/golang:1.14.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: cd Go/sequences && go test -v

workflows:
  build_and_test:
    jobs:
      - "node-run"
      - "go-run"
