name: run CI for oeis-ts
on: [push]

jobs:
  build:
    defaults:
      run:
        shell: bash
        working-directory: ./oeis-ts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "14"]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node and run ci
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      # - run: npm lint:prettier
      # - run: npm lint:eslint
      - run: npm test
